services:
  - type: web
    name: crm-nice
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn CRM_Nice.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CRM_Nice.settings.production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: crm-nice.onrender.com,.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        value: https://crm-nice.onrender.com,https://*.onrender.com


